{"timestamp": "2025-09-09T11:23:34.964619", "level": "ERROR", "logger": "mlPipelineLogger", "message": "'COLUMNS'", "module": "stage_07_evidently_monitoring", "function": "main", "line": 46, "process_id": 18784, "thread_id": 15204, "pipeline_stage": "unknown", "component": "unknown", "exception": "Traceback (most recent call last):\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\pipeline\\stage_07_evidently_monitoring.py\", line 18, in main\n    evidently_config = config.get_evidently_config()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\config\\configuration.py\", line 137, in get_evidently_config\n    schema = self.schema[\"COLUMNS\"]\n             ~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'COLUMNS'", "exception_type": "KeyError"}
{"timestamp": "2025-09-09T11:23:34.974697", "level": "ERROR", "logger": "mlPipelineLogger", "message": "'COLUMNS'", "module": "main", "function": "<module>", "line": 88, "process_id": 18784, "thread_id": 15204, "pipeline_stage": "unknown", "component": "unknown", "exception": "Traceback (most recent call last):\n  File \"D:\\MlOps PipeLine\\main.py\", line 85, in <module>\n    evidently_monitoring.main()\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\observability\\tracing.py\", line 62, in wrapper\n    result = func(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\pipeline\\stage_07_evidently_monitoring.py\", line 47, in main\n    raise e\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\pipeline\\stage_07_evidently_monitoring.py\", line 18, in main\n    evidently_config = config.get_evidently_config()\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\config\\configuration.py\", line 137, in get_evidently_config\n    schema = self.schema[\"COLUMNS\"]\n             ~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'COLUMNS'", "exception_type": "KeyError"}
{"timestamp": "2025-09-09T11:25:54.055164", "level": "ERROR", "logger": "mlpipeline.components.evidently_monitoring", "message": "Failed to generate data drift report: 'charmap' codec can't encode character '\\U0001f50d' in position 823: character maps to <undefined>", "module": "evidently_monitoring", "function": "generate_data_drift_report", "line": 59, "process_id": 3556, "thread_id": 19224, "pipeline_stage": "monitoring", "component": "evidently"}
{"timestamp": "2025-09-09T11:25:54.123254", "level": "ERROR", "logger": "mlpipeline.components.evidently_monitoring", "message": "Failed to generate comprehensive monitoring report: 'charmap' codec can't encode character '\\U0001f50d' in position 823: character maps to <undefined>", "module": "evidently_monitoring", "function": "generate_comprehensive_monitoring_report", "line": 165, "process_id": 3556, "thread_id": 19224, "pipeline_stage": "monitoring", "component": "evidently"}
{"timestamp": "2025-09-09T11:25:54.129525", "level": "ERROR", "logger": "mlPipelineLogger", "message": "'charmap' codec can't encode character '\\U0001f50d' in position 823: character maps to <undefined>", "module": "stage_07_evidently_monitoring", "function": "main", "line": 46, "process_id": 3556, "thread_id": 19224, "pipeline_stage": "unknown", "component": "unknown", "exception": "Traceback (most recent call last):\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\pipeline\\stage_07_evidently_monitoring.py\", line 28, in main\n    monitoring_report = evidently_monitoring.generate_comprehensive_monitoring_report(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\observability\\tracing.py\", line 62, in wrapper\n    result = func(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\components\\evidently_monitoring.py\", line 131, in generate_comprehensive_monitoring_report\n    drift_metrics = self.generate_data_drift_report(reference_data, current_data)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\observability\\tracing.py\", line 62, in wrapper\n    result = func(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\components\\evidently_monitoring.py\", line 40, in generate_data_drift_report\n    self._generate_drift_html_report(drift_metrics, html_path)\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\components\\evidently_monitoring.py\", line 435, in _generate_drift_html_report\n    f.write(html_content)\n  File \"C:\\Users\\abhes\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\encodings\\cp1252.py\", line 19, in encode\n    return codecs.charmap_encode(input,self.errors,encoding_table)[0]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nUnicodeEncodeError: 'charmap' codec can't encode character '\\U0001f50d' in position 823: character maps to <undefined>", "exception_type": "UnicodeEncodeError"}
{"timestamp": "2025-09-09T11:25:54.140699", "level": "ERROR", "logger": "mlPipelineLogger", "message": "'charmap' codec can't encode character '\\U0001f50d' in position 823: character maps to <undefined>", "module": "main", "function": "<module>", "line": 88, "process_id": 3556, "thread_id": 19224, "pipeline_stage": "unknown", "component": "unknown", "exception": "Traceback (most recent call last):\n  File \"D:\\MlOps PipeLine\\main.py\", line 85, in <module>\n    evidently_monitoring.main()\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\observability\\tracing.py\", line 62, in wrapper\n    result = func(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\pipeline\\stage_07_evidently_monitoring.py\", line 47, in main\n    raise e\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\pipeline\\stage_07_evidently_monitoring.py\", line 28, in main\n    monitoring_report = evidently_monitoring.generate_comprehensive_monitoring_report(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\observability\\tracing.py\", line 62, in wrapper\n    result = func(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\components\\evidently_monitoring.py\", line 131, in generate_comprehensive_monitoring_report\n    drift_metrics = self.generate_data_drift_report(reference_data, current_data)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\observability\\tracing.py\", line 62, in wrapper\n    result = func(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\components\\evidently_monitoring.py\", line 40, in generate_data_drift_report\n    self._generate_drift_html_report(drift_metrics, html_path)\n  File \"D:\\MlOps PipeLine\\src\\mlpipeline\\components\\evidently_monitoring.py\", line 435, in _generate_drift_html_report\n    f.write(html_content)\n  File \"C:\\Users\\abhes\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\encodings\\cp1252.py\", line 19, in encode\n    return codecs.charmap_encode(input,self.errors,encoding_table)[0]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nUnicodeEncodeError: 'charmap' codec can't encode character '\\U0001f50d' in position 823: character maps to <undefined>", "exception_type": "UnicodeEncodeError"}
